/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Panel.java to edit this template
 */
package com.franksuarez.tictactoe.form;

/**
 *
 * @author franksuarez
 */
public class TicTacToePanel extends java.awt.Panel {

    /**
     * Creates new form TicTacToePanel
     */
    public TicTacToePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button11 = new java.awt.Button();
        button12 = new java.awt.Button();
        button13 = new java.awt.Button();
        button21 = new java.awt.Button();
        button22 = new java.awt.Button();
        button23 = new java.awt.Button();
        button31 = new java.awt.Button();
        button32 = new java.awt.Button();
        button33 = new java.awt.Button();

        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        setLayout(new java.awt.GridLayout(3, 3));

        button11.setActionCommand("button");
        add(button11);

        button12.setActionCommand("button");
        add(button12);

        button13.setActionCommand("button");
        add(button13);

        button21.setActionCommand("button");
        add(button21);

        button22.setActionCommand("button");
        button22.setLabel("button7");
        add(button22);

        button23.setActionCommand("button");
        button23.setLabel("button5");
        add(button23);

        button31.setActionCommand("button");
        button31.setLabel("button6");
        add(button31);

        button32.setActionCommand("button");
        button32.setLabel("button8");
        add(button32);

        button33.setActionCommand("button");
        button33.setLabel("button9");
        add(button33);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button11;
    private java.awt.Button button12;
    private java.awt.Button button13;
    private java.awt.Button button21;
    private java.awt.Button button22;
    private java.awt.Button button23;
    private java.awt.Button button31;
    private java.awt.Button button32;
    private java.awt.Button button33;
    // End of variables declaration//GEN-END:variables
}
