/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.franksuarez.tictactoe.ui;

/**
 *
 * @author franksuarez
 */
public class ImageTTTFrame extends javax.swing.JFrame {

    /**
     * Creates new form ImageTTTFrame
     */
    public ImageTTTFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ticTacToeBoard1 = new com.franksuarez.tictactoe.model.TicTacToeBoard();
        imageJComponent1 = new com.franksuarez.tictactoe.beans.ImageJComponent();
        tTTJPanel1 = new com.franksuarez.tictactoe.ui.TTTJPanel();
        jLblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        imageJComponent1.setImagePath("goku.png");
        imageJComponent1.setInheritsPopupMenu(true);

        tTTJPanel1.setMaximumSize(new java.awt.Dimension(324, 324));
        tTTJPanel1.setOpaque(false);
        tTTJPanel1.setStatusLabel(jLblStatus);

        jLblStatus.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLblStatus.setText("Tic-Tac-Toe");

        javax.swing.GroupLayout imageJComponent1Layout = new javax.swing.GroupLayout(imageJComponent1);
        imageJComponent1.setLayout(imageJComponent1Layout);
        imageJComponent1Layout.setHorizontalGroup(
            imageJComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imageJComponent1Layout.createSequentialGroup()
                .addContainerGap(559, Short.MAX_VALUE)
                .addGroup(imageJComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imageJComponent1Layout.createSequentialGroup()
                        .addComponent(tTTJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imageJComponent1Layout.createSequentialGroup()
                        .addComponent(jLblStatus)
                        .addGap(85, 85, 85))))
        );
        imageJComponent1Layout.setVerticalGroup(
            imageJComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imageJComponent1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLblStatus)
                .addGap(49, 49, 49)
                .addComponent(tTTJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageJComponent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageJComponent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public static void listLookAndFeel() {
        System.out.println("Installed Look and Feels:");
        for (javax.swing.UIManager.LookAndFeelInfo info: javax.swing.UIManager.getInstalledLookAndFeels() ){
            System.out.printf("%s%n",info.getName());
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ImageTTTFrame.listLookAndFeel();
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Mac OS X".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageTTTFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageTTTFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageTTTFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageTTTFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageTTTFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.franksuarez.tictactoe.beans.ImageJComponent imageJComponent1;
    private javax.swing.JLabel jLblStatus;
    private com.franksuarez.tictactoe.ui.TTTJPanel tTTJPanel1;
    private com.franksuarez.tictactoe.model.TicTacToeBoard ticTacToeBoard1;
    // End of variables declaration//GEN-END:variables
}
