/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.franksuarez.tictactoe.ui;

import com.franksuarez.tictactoe.beans.ImageComponent;
import com.franksuarez.tictactoe.model.TicTacToeBoard;
import java.util.function.Consumer;

/**
 *
 * @author franksuarez
 */
public class TTTImageJPanel extends javax.swing.JPanel {

    private String defaultText = "Tic-Tac-Toe";
    
    private javax.swing.JLabel statusLabel;

    public javax.swing.JLabel getStatusLabel() {
        return this.statusLabel;
    }

    public void setStatusLabel(javax.swing.JLabel statusLabel) {
        this.statusLabel = statusLabel;
    }

    
    /**
     * Creates new form TTTImageJPanel
     */
    public TTTImageJPanel() {
        initComponents();
        this.board.initialize();
    }

    private void makeMove(ImageComponent src, int x, int y, String player1Token, String player2Token) {
        System.out.println("made move");

        this.board.makeMove(x, y);

        TicTacToeBoard.Player currentPlayer = this.board.getCurrentPlayer();
        if (currentPlayer == TicTacToeBoard.Player.PLAYER1) {
            src.setFilePath(player1Token);
        } else if (currentPlayer == TicTacToeBoard.Player.PLAYER2) {
            src.setFilePath(player2Token);
        }

        src.setEnabled(false);

        this.board.checkForWinner();
        if (this.board.getWinnerExists()) {
            System.out.println("winner exists");
            this.disableAllButtons();

            TicTacToeBoard.Player winningPlayer = this.board.getWinningPlayer();

            //System.out.printf("Winner: %s%n",winningPlayer.name());
            if (this.statusLabel != null) {
                this.statusLabel.setText(
                        String.format(
                                "The winner is %s", winningPlayer.name()
                        )
                );
            }

        }
        this.board.switchPlayer();
        this.repaint();
    }

    public void buttonClick(ImageComponent src, int x, int y, String player1Token, String player2Token) {
        if (src.isEnabled()) {
            this.makeMove(src, x, y, player1Token, player2Token);
        }
    }

    public void forEachButton(Consumer<ImageComponent> c) {
        ImageComponent[] icArray = new ImageComponent[]{
            this.imageComponent1,
            this.imageComponent2,
            this.imageComponent3,
            this.imageComponent4,
            this.imageComponent5,
            this.imageComponent6,
            this.imageComponent7,
            this.imageComponent8,
            this.imageComponent9
        };

        for (ImageComponent ic : icArray) {
            //ic.setEnabled(false);
            c.accept(ic);
        }
    }

    public void disableAllButtons() {
        this.forEachButton((i) -> {
            i.setEnabled(false);
        });
    }

    public void enableAllButtons() {
        this.forEachButton((i) -> {
            i.setEnabled(true);
        });
    }

    public void clearButtons() {
        this.forEachButton((i) -> {
            i.setFilePath("");
        });
        //this.repaint();
    }

    public void reset() {
        this.board.reset();
        
        enableAllButtons();
        clearButtons();
        if (this.statusLabel != null) {
            this.statusLabel.setText(defaultText);
        }
        this.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        board = new com.franksuarez.tictactoe.model.TicTacToeBoard();
        imageComponent1 = new com.franksuarez.tictactoe.beans.ImageComponent();
        imageComponent2 = new com.franksuarez.tictactoe.beans.ImageComponent();
        imageComponent3 = new com.franksuarez.tictactoe.beans.ImageComponent();
        imageComponent4 = new com.franksuarez.tictactoe.beans.ImageComponent();
        imageComponent5 = new com.franksuarez.tictactoe.beans.ImageComponent();
        imageComponent6 = new com.franksuarez.tictactoe.beans.ImageComponent();
        imageComponent7 = new com.franksuarez.tictactoe.beans.ImageComponent();
        imageComponent8 = new com.franksuarez.tictactoe.beans.ImageComponent();
        imageComponent9 = new com.franksuarez.tictactoe.beans.ImageComponent();
        boardImage = new com.franksuarez.tictactoe.beans.ImageComponent();

        setOpaque(false);
        setLayout(null);

        imageComponent1.setImageCentered(true);
        imageComponent1.setOffsetX(10);
        imageComponent1.setOffsetY(2);
        imageComponent1.setPaintBackground(false);
        imageComponent1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageComponent1MouseClicked(evt);
            }
        });
        add(imageComponent1);
        imageComponent1.setBounds(0, 0, 150, 150);

        imageComponent2.setImageCentered(true);
        imageComponent2.setPaintBackground(false);
        imageComponent2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageComponent2MouseClicked(evt);
            }
        });
        add(imageComponent2);
        imageComponent2.setBounds(180, 0, 150, 150);

        imageComponent3.setImageCentered(true);
        imageComponent3.setPaintBackground(false);
        imageComponent3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageComponent3MouseClicked(evt);
            }
        });
        add(imageComponent3);
        imageComponent3.setBounds(360, 0, 150, 150);

        imageComponent4.setImageCentered(true);
        imageComponent4.setPaintBackground(false);
        imageComponent4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageComponent4MouseClicked(evt);
            }
        });
        add(imageComponent4);
        imageComponent4.setBounds(-4, 186, 150, 140);

        imageComponent5.setImageCentered(true);
        imageComponent5.setPaintBackground(false);
        imageComponent5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageComponent5MouseClicked(evt);
            }
        });
        add(imageComponent5);
        imageComponent5.setBounds(186, 186, 140, 140);

        imageComponent6.setImageCentered(true);
        imageComponent6.setPaintBackground(false);
        imageComponent6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageComponent6MouseClicked(evt);
            }
        });
        add(imageComponent6);
        imageComponent6.setBounds(366, 186, 140, 140);

        imageComponent7.setImageCentered(true);
        imageComponent7.setPaintBackground(false);
        imageComponent7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageComponent7MouseClicked(evt);
            }
        });
        add(imageComponent7);
        imageComponent7.setBounds(0, 360, 150, 150);

        imageComponent8.setImageCentered(true);
        imageComponent8.setPaintBackground(false);
        imageComponent8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageComponent8MouseClicked(evt);
            }
        });
        add(imageComponent8);
        imageComponent8.setBounds(180, 360, 150, 150);

        imageComponent9.setImageCentered(true);
        imageComponent9.setPaintBackground(false);
        imageComponent9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageComponent9MouseClicked(evt);
            }
        });
        add(imageComponent9);
        imageComponent9.setBounds(360, 360, 150, 150);

        boardImage.setFilePath("blank.png");
        add(boardImage);
        boardImage.setBounds(0, 0, 512, 512);
    }// </editor-fold>//GEN-END:initComponents

    private void imageComponent1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageComponent1MouseClicked
        this.buttonClick((ImageComponent) evt.getSource(), 0, 2, "xleft.png", "oleft.png");
    }//GEN-LAST:event_imageComponent1MouseClicked

    private void imageComponent2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageComponent2MouseClicked
        this.buttonClick((ImageComponent) evt.getSource(), 1, 2, "xmid.png", "omid.png");
    }//GEN-LAST:event_imageComponent2MouseClicked

    private void imageComponent3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageComponent3MouseClicked
        this.buttonClick((ImageComponent) evt.getSource(), 2, 2, "xright.png", "oright.png");
    }//GEN-LAST:event_imageComponent3MouseClicked

    private void imageComponent4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageComponent4MouseClicked
        this.buttonClick((ImageComponent) evt.getSource(), 0, 1, "xleft.png", "oleft.png");
    }//GEN-LAST:event_imageComponent4MouseClicked

    private void imageComponent5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageComponent5MouseClicked
        this.buttonClick((ImageComponent) evt.getSource(), 1, 1, "xmid.png", "omid.png");
    }//GEN-LAST:event_imageComponent5MouseClicked

    private void imageComponent6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageComponent6MouseClicked
        // TODO add your handling code here:
        this.buttonClick((ImageComponent) evt.getSource(), 2, 1, "xright.png", "oright.png");
    }//GEN-LAST:event_imageComponent6MouseClicked

    private void imageComponent7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageComponent7MouseClicked
        // TODO add your handling code here:
        this.buttonClick((ImageComponent) evt.getSource(), 0, 0, "xleft.png", "oleft.png");
    }//GEN-LAST:event_imageComponent7MouseClicked

    private void imageComponent8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageComponent8MouseClicked
        // TODO add your handling code here:
        this.buttonClick((ImageComponent) evt.getSource(), 1, 0, "xmid.png", "omid.png");
    }//GEN-LAST:event_imageComponent8MouseClicked

    private void imageComponent9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageComponent9MouseClicked
        // TODO add your handling code here:
        this.buttonClick((ImageComponent) evt.getSource(), 2, 0, "xright.png", "oright.png");
    }//GEN-LAST:event_imageComponent9MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.franksuarez.tictactoe.model.TicTacToeBoard board;
    private com.franksuarez.tictactoe.beans.ImageComponent boardImage;
    private com.franksuarez.tictactoe.beans.ImageComponent imageComponent1;
    private com.franksuarez.tictactoe.beans.ImageComponent imageComponent2;
    private com.franksuarez.tictactoe.beans.ImageComponent imageComponent3;
    private com.franksuarez.tictactoe.beans.ImageComponent imageComponent4;
    private com.franksuarez.tictactoe.beans.ImageComponent imageComponent5;
    private com.franksuarez.tictactoe.beans.ImageComponent imageComponent6;
    private com.franksuarez.tictactoe.beans.ImageComponent imageComponent7;
    private com.franksuarez.tictactoe.beans.ImageComponent imageComponent8;
    private com.franksuarez.tictactoe.beans.ImageComponent imageComponent9;
    // End of variables declaration//GEN-END:variables

}
