/**
 * 
*/
package com.franksuarez.tictactoe.ui;

import com.franksuarez.tictactoe.model.TicTacToeBoard;

/**
 *
 * @author franksuarez
 */
public class TTTJPanel extends javax.swing.JPanel {

    private TicTacToeBoard board;
    public javax.swing.JLabel statusLabel;

    public javax.swing.JLabel getStatusLabel() {
        return this.statusLabel;
    }
    
    public void setStatusLabel(javax.swing.JLabel statusLabel) {
        javax.swing.JLabel oldStatusLabel = this.statusLabel;
        firePropertyChange("statusLabel", oldStatusLabel, statusLabel);
        this.statusLabel = statusLabel;
    }
    
    private void makeMove(javax.swing.JButton src, int x, int y) {
        this.board.makeMove(x, y);

        // get current player
        char currentPlayerToken = this.board.getCurrentPlayerToken();

        src.setText(String.valueOf(currentPlayerToken));
        src.setEnabled(false);

        // check for winner
        this.board.checkForWinner();
        if (this.board.getWinnerExists()) {
            System.out.println("winner exists");

            TicTacToeBoard.Player winningPlayer = this.board.getWinningPlayer();

            char winningPlayerToken = this.board.getPlayerToken(winningPlayer);

            statusLabel.setText(String.format("Winner: %c", winningPlayerToken));

            // Disable all buttons
            for (javax.swing.JButton b : new javax.swing.JButton[]{
                this.jButton1,
                this.jButton2,
                this.jButton3,
                this.jButton4,
                this.jButton5,
                this.jButton6,
                this.jButton7,
                this.jButton8,
                this.jButton9
            }) {
                b.setEnabled(false);
            }
        }
        this.board.switchPlayer();
    }

    // TODO:
    public void reset() {

        for (javax.swing.JButton b : new javax.swing.JButton[]{
            this.jButton1,
            this.jButton2,
            this.jButton3,
            this.jButton4,
            this.jButton5,
            this.jButton6,
            this.jButton7,
            this.jButton8,
            this.jButton9
        }) {
            b.setEnabled(true);
            b.setText("");
        }

        this.board.reset();
    }

    /**
     * Creates new form TTTJPanel
     */
    public TTTJPanel() {
        initComponents();

        this.board = new TicTacToeBoard();
        this.board.initialize();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonTemplate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        jButtonTemplate.setFont(new java.awt.Font("Helvetica Neue", 0, 72)); // NOI18N
        jButtonTemplate.setText("jButton12");
        jButtonTemplate.setPreferredSize(new java.awt.Dimension(100, 100));

        jButton1.setFont(jButtonTemplate.getFont());
        jButton1.setMaximumSize(jButtonTemplate.getMaximumSize());
        jButton1.setMinimumSize(jButtonTemplate.getMinimumSize());
        jButton1.setPreferredSize(jButtonTemplate.getPreferredSize());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(jButtonTemplate.getFont());
        jButton2.setMaximumSize(jButtonTemplate.getMaximumSize());
        jButton2.setMinimumSize(jButtonTemplate.getMinimumSize());
        jButton2.setPreferredSize(jButtonTemplate.getPreferredSize());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(jButtonTemplate.getFont());
        jButton3.setMaximumSize(jButtonTemplate.getMaximumSize());
        jButton3.setMinimumSize(jButtonTemplate.getMinimumSize());
        jButton3.setPreferredSize(jButtonTemplate.getPreferredSize());
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(jButtonTemplate.getFont());
        jButton4.setMaximumSize(jButtonTemplate.getMaximumSize());
        jButton4.setMinimumSize(jButtonTemplate.getMinimumSize());
        jButton4.setPreferredSize(jButtonTemplate.getPreferredSize());
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(jButtonTemplate.getFont());
        jButton5.setMaximumSize(jButtonTemplate.getMaximumSize());
        jButton5.setMinimumSize(jButtonTemplate.getMinimumSize());
        jButton5.setPreferredSize(jButtonTemplate.getPreferredSize());
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(jButtonTemplate.getFont());
        jButton6.setMaximumSize(jButtonTemplate.getMaximumSize());
        jButton6.setMinimumSize(jButtonTemplate.getMinimumSize());
        jButton6.setPreferredSize(jButtonTemplate.getPreferredSize());
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(jButtonTemplate.getFont());
        jButton7.setMaximumSize(jButtonTemplate.getMaximumSize());
        jButton7.setMinimumSize(jButtonTemplate.getMinimumSize());
        jButton7.setPreferredSize(jButtonTemplate.getPreferredSize());
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(jButtonTemplate.getFont());
        jButton8.setMaximumSize(jButtonTemplate.getMaximumSize());
        jButton8.setMinimumSize(jButtonTemplate.getMinimumSize());
        jButton8.setPreferredSize(jButtonTemplate.getPreferredSize());
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(jButtonTemplate.getFont());
        jButton9.setMaximumSize(jButtonTemplate.getMaximumSize());
        jButton9.setMinimumSize(jButtonTemplate.getMinimumSize());
        jButton9.setPreferredSize(jButtonTemplate.getPreferredSize());
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.makeMove(this.jButton1, 0, 2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.makeMove(this.jButton2, 1, 2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.makeMove(this.jButton3, 2, 2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.makeMove(this.jButton4, 0, 1);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.makeMove(this.jButton5, 1, 1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.makeMove(this.jButton6, 2, 1);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.makeMove(this.jButton7, 0, 0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.makeMove(this.jButton8, 1, 0);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        this.makeMove(this.jButton9, 2, 0);
    }//GEN-LAST:event_jButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonTemplate;
    // End of variables declaration//GEN-END:variables
}
