// TODO: Move app start to TicTacToeApp
// TODO: Remove






/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.franksuarez.tictactoe;

public class App {


    public static void main(String[] args) {
        
    }
}
