/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.franksuarez.tictactoe;

import com.franksuarez.tictactoe.form.TicTacToeFrame;
import com.franksuarez.tictactoe.ui.TicTacToeApp;

public class App {


    public static void main(String[] args) {
        TicTacToeApp t = new TicTacToeApp();
        t.start();
        
        //TicTacToeFrame t = new TicTacToeFrame();
        //t.setVisible(true);
    }
}
