/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.franksuarez.tictactoe;

import com.franksuarez.tictactoe.ui.TicTacToeApp;
import com.franksuarez.tictactoe.ui.TicTacToePanel;

public class App {


    public static void main(String[] args) {
        
        //TicTacToePanel t = new TicTacToePanel();
        //t.start();
        
        TicTacToeApp t = new TicTacToeApp();
        t.start();
    }
}
